"""Constants for the Weishaupt WCM-COM integration."""

DOMAIN = 'weishaupt_wcm_com'
NAME_PREFIX = "Weishaupt "

OIL_CONSUMPTION_KEY = "Oil Meter"
OUTSIDE_TEMPERATURE_KEY = "Outside Temperature"
WARM_WATER_TEMPERATURE_KEY = "Warm Water Temperature"
FLOW_TEMPERATURE_KEY = "Flow Temperature"
FLUE_GAS_TEMPERATURE_KEY = "Flue Gas Temperature"
MIXED_EXTERNAL_TEMPERATURE_KEY = "Mixed External Temperature"
ROOM_TEMPERATURE_KEY = "Room Temperature"
OPERATING_MODE_KEY = "Operating Mode"
OPERATING_PHASE_KEY = "Operating Phase"
PUMP_KEY = "Pump"
WARM_WATER_KEY = "Warm Water"
FLAME_KEY = "Flame"
ERROR_KEY = "Error"
GAS_VALVE_1_KEY = "Gas Valve 1"
GAS_VALVE_2_KEY = "Gas Valve 2"
HEATING_KEY = "Heating"
HEAT_DEMAND_KEY = "Heat Demand"
HEATING_SPECIAL_LEVEL_KEY = "Heating Special Level"
TIME_SINCE_LAST_SERVICE_KEY = "Time Since Last Service"
BURNER_STARTS_KEY = "Burner Starts"
BURNER_HOURS_KEY = "Burner Hours"
BURNER_LOAD_KEY = "Burner Load"
SYSTEM_FROST_PROTECTION_KEY = "System Frost Protection"
MIN_FLOW_TEMP_KEY = "Min Flow Temp"
MAX_FLOW_TEMP_KEY = "Max Flow Temp"
FLOW_TEMP_HYSTERESIS_KEY = "Flow Temp Hysteresis"
BURNER_LOCKOUT_TIME_KEY = "Burner Lockout Time"
MAX_DHW_OUTPUT_KEY = "Max DHW Output"
MAX_DHW_CHARGE_TIME_KEY = "Max DHW Charge Time"
